COMMONSENSE_MAPPING = {'Antonym': 'antonym', 
	'AtLocation': 'at location', 
	'CapableOf': 'capable of', 
	'Causes': 'causes', 
	'CausesDesire': 'causes desire', 
	'CreatedBy': 'created by', 
	'DefinedAs': 'defined as', 
	'DerivedFrom': 'derived from', 
	'Desires': 'desires', 
	'DistinctFrom': 'destinct from', 
	'Entails': 'entails', 
	'EtymologicallyDerivedFrom': 'etymologically derived from', 
	'EtymologicallyRelatedTo': 'etymologically related to', 
	'FormOf': 'form of', 
	'HasA': 'has a', 
	'HasContext': 'has context', 
	'HasFirstSubevent': 'has first subevent', 
	'HasLastSubevent': 'has last subevent', 
	'HasPrerequisite': 'has prerequisite', 
	'HasProperty': 'has property', 
	'HasSubevent': 'has subevent', 
	'InstanceOf': 'instance of', 
	'IsA': 'is a', 
	'LocatedNear': 'location near', 
	'MadeOf': 'made of', 
	'MannerOf': 'manner of', 
	'MotivatedByGoal': 'motivated by goal', 
	'NotCapableOf': 'not capable of', 
	'NotDesires': 'not desires', 
	'NotHasProperty': 'not has property', 
	'PartOf': 'part of', 
	'ReceivesAction': 'received action', 
	'RelatedTo': 'related to', 
	'SimilarTo': 'similar to', 
	'SymbolOf': 'symbol of', 
	'Synonym': 'synonym', 
	'UsedFor': 'used for', 
        'DesireOf': 'desire of',
        'InheritsFrom': 'inherits from',
        'LocationOfAction': 'location of action',
	'dbpedia/capital': 'capital', 
	'dbpedia/field': 'field', 
	'dbpedia/genre': 'genre', 
	'dbpedia/genus': 'genus', 
	'dbpedia/influencedBy': 'influenced by', 
	'dbpedia/knownFor': 'known for', 
	'dbpedia/language': 'language', 
	'dbpedia/leader': 'leader', 
	'dbpedia/occupation': 'occupation', 
	'dbpedia/product': 'product'}